<?php
echo "<br><center><h1> EXP2(B)(94) </h1></center>";
$Month= "Nov";

switch($Month)
{
    case 'Jan':
        echo "Month is January";
        break;

     case 'Feb':
        echo "Month is Februry";
        break;

    case 'Mar':
        echo "Month is March";
         break;

    case 'Apr':
        echo "Month is April";
        break;

    case 'May':
        echo "Month is May";
        break;

    case 'Jun':
        echo "Month is June";
        break;

    case 'Jul':
        echo "Month is July";
        break;

    case 'Aug':
        echo "Month is August";
        break;

    case 'Sep':
        echo "Month is September";
        break;

    case 'Oct':
        echo "Month is October";
         break;

    case 'Nov':
        echo "Month is November";
        break;

    case 'Dec':
        echo "Month is December";
        break;
    default :
        echo "that month is not available";
        break;
}
?>